/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export { Vault } from "./ethers-contracts/factories/Vault";

export { Vault__factory } from "./ethers-contracts/factories/Vault__factory";

