/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BscVault } from "./BscVault";


export { BscVault__factory } from "./factories/BscVault__factory";

